server:
  port: 7000
spring:
  application:
    name: shiro
  datasource:
    url: jdbc:mysql://localhost:3306/spring-shiro?serverTimezone=GMT%2B8&useSSL=true&useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  cache:
    type: ehcache
    ehcache:
      config: config/ehcache.xml
  redis:
        host: localhost
        port: 6379
        password:
        #连接超时时间（毫秒）
        timeout: 10000
        pool:
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 10
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  type-aliases-package: com.yaa.cms.model
